# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "v2" ]
  pull_request:
    branches: [ "main", "v2" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: 'letheanVPN/desktop'
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean
          build-platform: linux/amd64
          deno-build: "npm run server:build:linux"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: v2.3.1
  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          repository: 'letheanVPN/desktop'
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean
          build-platform: darwin/universal
          deno-build: "npm run server:build:macos-intel"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: "v2.3.1"
          go-version: ^1.18
          sign: "false"
          sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
          sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
          sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
          sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
          sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
          sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
          sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}

  windows:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          repository: 'letheanVPN/desktop'
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean.exe
          build-platform: windows/amd64
          deno-build: "npm run server:build:windows"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: v2.3.1
          go-version: ^1.18
          nsis: 'false'
  windows-nsis:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          repository: 'letheanVPN/desktop'
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: lethean.exe
          build-platform: windows/amd64
          deno-build: "npm run server:build:windows"
          deno-working-directory: "server"
          wails-build-webview2: "embed"
          wails-version: v2.3.1
          go-version: ^1.18
          nsis: "true"
